[package]
name = "lol_store"
version = "0.1.0"
authors = ["Adrian Brink <adrian@brink-holdings.com>"]

[dependencies]
dotenv = "0.8.0"
serde = "0.8.20"
serde_json = "0.8.4"
serde_derive = "0.8.20"
hyper = "0.9.14"
diesel = "0.9.1"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }