version: '2'

services: 
    redis:
        image: redis
        ports: 
            - '6379:6379'
        volumes: 
            - 'redis:/var/lib/redis/data'
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
    # lol_store:
    #     depends_on: 
    #         - 'redis'
    #         - 'postgres'
    #     build: .
    #     command: 'cargo run'
    #     volumes: 
    #         - '.:/source'
    #     links: 
    #         - 'redis'
    #         - 'postgres'

volumes: 
    redis:
    postgres: