version: '2'

services: 
    redis:
        image: redis
        volumes: 
            - 'redis:/var/lib/redis/data'
    postgres:
        image: postgres
        volumes:
            - 'postgres:/var/lib/postgresql/data'
    lol_store:
        depends_on: 
            - 'redis'
            - 'postgres'
        command: 'cargo test'
        build: .
        volumes: 
            - '.:/source'
        links: 
            - 'redis'
            - 'postgres'

volumes: 
    redis:
    postgres: