version: '2'

services: 
    postgres:
        image: 'postgres'
        ports:
            - '5432:5432'
    redis:
        image: redis
        ports:
            - '6379:6379'
    server:
        build: .
        depends_on: 
            - 'postgres'
            - 'redis'
        links: 
            - redis
            - postgres