version: '2'

services: 
    redis:
        image: redis
        volumes: 
            - 'redis:/var/lib/redis/data'
    postgres:
        image: postgres
        volumes:
            - 'postgres:/var/lib/postgresql/data'
    migration:
        build: .
        command: bash -c "sleep 10 && diesel setup --database-url='postgres://postgres@postgres/lol_store' && diesel migration run"
        depends_on: 
            - 'postgres'
    lol_store:
        depends_on: 
            - 'redis'
            - 'migration'
        command: bash -c "sleep 15 && cargo test"
        build: .
        volumes: 
            - '.:/source'
        links: 
            - 'redis'
            - 'postgres'

volumes: 
    redis:
    postgres: